version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-https://api.bayreshub.com/api}
      - NEXT_PUBLIC_CLIENT_URL=${NEXT_PUBLIC_CLIENT_URL:-https://panel.bayreshub.com}
      - NEXT_PUBLIC_WEBHOOK_URL=${NEXT_PUBLIC_WEBHOOK_URL:-https://api.bayreshub.com/external/leads/webhook}
      - NEXT_PUBLIC_NOTIFICATIONS_URL=${NEXT_PUBLIC_NOTIFICATIONS_URL:-https://api.bayreshub.com/notifications}
      - NEXT_PUBLIC_HEALTH_CHECK_URL=${NEXT_PUBLIC_HEALTH_CHECK_URL:-https://api.bayreshub.com/health}
      - NEXT_PUBLIC_UPLOADS_URL=${NEXT_PUBLIC_UPLOADS_URL:-https://api.bayreshub.com/uploads}
    restart: unless-stopped
    networks:
      - bayres-network

networks:
  bayres-network:
    driver: bridge 